language: node_js
node_js:
- '0.12'
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: s3
  bucket: json.kmc.io
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  skip_cleanup: true
  local-dir: dist
  acl: public_read
  on:
    repo: kmctown/json.kmc.io
env:
  global:
  - secure: KjH33pwTNw8ngsTLiq0SCXB+x0Hoa/BBq365XW5q49Kz0RZ4iSrN4pwd53LHPZdSyEnWaIKZOm6mpszQIAXa7mnCdhYQ6iX7WMncatBJldS1Opr4FSVkVeYaoiVxkoo8YPgI7ugnx3hNG/kS0zj5v3f9kxNk+KIXFCFrcRMlKDLGStT4BZN0Qe/pyGUdD51VKwEiw5I9QB7nmE5YNZKI0lbDUtxWkJcZ3Fwz/oJJ7J24W+wctstjQlaCB0hO+vPDWzOCxHBaWm1aBmFxGKi7ZA1/d6L42Pb0rXNyOd0Bw1KkqfP9tIyesen/V0+y8ubFvESpNGSExUDI6gsOEOJbKWJKLAtnQ67VIdVc5r/DWmbMGcgCqwMAWVPNjZLueRvVhGpDYu3tRinqGMs/AUc2N4mNMjdt+AkQCWDl586NKerQBF8ut62o3nlAYH/SArtSI3kr2JIDM2zUh4CCBpYuNi3z0v3SGMNxysm92kiYU7iyajsqWsxFNMnmo+I+mhKiX/V1ILDQ3/6GP5z8m6fbvGHuqxOapnRhF+5yDeIk7lTGqj2GZDenDBgABHMYpr3YciFMPwZUEnI0OnfxicV6LF7SH+dbDLYEN+R/1pNYsjg9vZ95tRvdXt7qtkH0k5XqtTQuRN/1OCMvVPkSCpkVOEdvm0IsXmRHkio0zGLJVuM=
  - secure: AszwUpOzb7B6TLmGMm4Fi3745U26U+iTsbl0/Jn9anMLu50r4zH34Xjg1lrgiS/hge9SrKksq+LK+gQuzRwdU6YThztpMFnzsWpBycXm9SmnnsE8bQsAiRipjWsv885sOqmEXmvl22i8dcMnOqN+Fl+0JfBiG1QsbgumqyYsgPwi/kjRCNtzDEHuEgJLh96b2CLDOhSvfo1WvZsMCHfaiybcEcREajkcTGUnl7lglj82o3Wf7MhTxrT86RliHYBvlk0ceQkvFJQ/pA3ndc6zVe8hdLSQK2l8NC8OVApKt4fLG9NMlyXaQO39jRAMoiBHjWV4l4BirQiThsossiox5MMLB8NfXo+U9hjJR5f6DG1HGVUoz/lgvJc9g+FbrebEe92RefGa+rSsXCY6QUD04hG7jwwLF4nku0uOScPMIjpe3KJ4yu1GXi4o33Yyg2Y5bz3JBguylC8gnxzxXfgVWfZQ7QU5JpfuNiMfYchltgkndB8NY8WJynOAW2daRSUvHdt2zdwgMzBm2QlKZG/JE5fVtzhbobyM52fqLIesuafUFKArJrKGr/wLdZjfHHZb1iBQTg32EKkynX5gZBx1JPJv6vjbnARbPx4PmlE/1DoQtx2nVutM2sVZkAaw+uwsfdwmcb8jMVwDps5PWyApfZBK/ZGaVJ8cEjoe9P0AETk=
